Repository Dumboz/yalp, pull requests merged in 2022-01, with the labels that each got.

#31 Update Global Style Component
  package-lock.json
  package.json
  src/styles/global.styled.js
Labels: config

#43 Modify Star, Rating, Button Component
  .storybook/preview.js
  src/components/Button/Button.jsx
  src/components/Button/Button.stories.jsx
  src/components/Button/Button.styeld.jsx
  src/components/Rating/Rating.jsx
  src/components/Rating/Rating.stories.jsx
  src/components/Rating/Rating.styled.jsx
  src/components/Star/Star.jsx
  src/components/Star/Star.stories.jsx
  src/index.js
  src/styles/theme.js
Labels: enhancement, components

#87 Update Pagenation & SearchForm & Redux state update logic
  client/.storybook/preview.js
  client/package.json
  client/src/components/ArrowButton/ArrowButton.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Pagenation/Pagenation.jsx
  client/src/components/Pagenation/Pagenation.stories.jsx
  client/src/components/Pagenation/Pagenation.styled.jsx
  client/src/components/SearchForm/SearchForm.jsx
  client/src/index.js
  client/src/pages/App/App.jsx
  client/src/store/businesses.js
  client/src/store/features/businesses.js
  client/src/store/features/index.js
  client/src/store/index.js
Labels: enhancement, config, components

#95 Update SearchForm, SearchPage, Icon
  client/src/components/Icon/Icon.jsx
  client/src/components/Icon/Icon.stories.jsx
  client/src/components/InitSVG/InitSVG.jsx
  client/src/components/Pagenation/Pagenation.jsx
  client/src/components/SearchForm/SearchForm.jsx
  client/src/pages/SearchPage/SearchPage.jsx
  server/controllers/autocomplete/index.js
  server/routes/autocomplete.js
Labels: bug, enhancement, components

#100 Layout SearchPage
  client/src/components/FilterSection/FilterSection.styled.jsx
  client/src/components/Pagenation/Pagenation.styled.jsx
  client/src/components/TitleWrapper/TitleWrapper.jsx
  client/src/components/TitleWrapper/TitleWrapper.stories.jsx
  client/src/index.js
  client/src/layouts/GEO/GEO.styled.jsx
  client/src/pages/SearchPage/SearchPage.jsx
  client/src/pages/SearchPage/SearchPage.styled.jsx
Labels: enhancement, components

#103 Debug Infinite Loop & Update SearchForm Query
  client/src/components/Pagenation/Pagenation.jsx
  client/src/components/SearchForm/SearchForm.jsx
  client/src/store/businesses.js
Labels: bug

#105 Create PhotoModal Component
  client/src/components/Icon/Icon.jsx
  client/src/components/Icon/Icon.stories.jsx
  client/src/components/InitSVG/InitSVG.jsx
  client/src/components/Modal/Modal.jsx
  client/src/components/Modal/Modal.stories.jsx
  client/src/components/Modal/Modal.styled.jsx
  client/src/components/TitleWrapper/TitleWrapper.jsx
  client/src/components/index.js
  client/src/layouts/PhotoModal/PhotoModal.jsx
  client/src/layouts/PhotoModal/PhotoModal.styled.jsx
  client/src/layouts/index.js
Labels: enhancement, components

#108 Merge & Update Code
  client/src/components/Comment/Comment.jsx
  client/src/components/Comment/Comment.stories.jsx
  client/src/components/Comment/Comment.styled.jsx
  client/src/components/CommentList/CommentList.jsx
  client/src/components/CommentList/CommentList.stories.jsx
  client/src/components/CommentList/CommentList.styled.jsx
  client/src/components/Icon/Icon.jsx
  client/src/components/Icon/Icon.stories.jsx
  client/src/components/InitSVG/InitSVG.jsx
  client/src/components/Modal/Modal.jsx
  client/src/components/SearchForm/SearchForm.jsx
  client/src/components/TitleWrapper/TitleWrapper.jsx
  client/src/components/TitleWrapper/TitleWrapper.stories.jsx
  client/src/components/TitleWrapper/TitleWrapper.styled.jsx
  client/src/layouts/GEO/GEO.styled.jsx
  client/src/pages/SearchPage/SearchPage.jsx
  client/src/pages/SearchPage/SearchPage.styled.jsx
Labels: fix

#111 Remove Logic that use Businesses state (in Pagenation)
  client/src/components/Pagenation/Pagenation.jsx
  client/src/components/Pagenation/Pagenation.styled.jsx
  client/src/pages/SearchPage/SearchPage.jsx
  client/src/pages/SearchPage/SearchPage.styled.jsx
Labels: bug

#117 Create DetailBanner, Carousel and Modify Modal, PhotoModal component
  client/package.json
  client/src/components/Comment/Comment.jsx
  client/src/components/Comment/Comment.styled.jsx
  client/src/components/Modal/Modal.jsx
  client/src/layouts/DetailBanner/Carousel.jsx
  client/src/layouts/DetailBanner/DetailBanner.jsx
  client/src/layouts/DetailBanner/DetailBanner.styled.jsx
  client/src/layouts/PhotoModal/PhotoModal.jsx
  client/src/layouts/index.js
  client/src/pages/DetailPage/DetailPage.jsx
  client/src/styles/theme.js
  client/src/utils/time/index.js
  client/src/utils/time/makeTimeString.js
Labels: enhancement, components

#121 feat: Create ScrollToTop Component #80
  client/src/components/ScrollToTop/ScrollToTop.jsx
  client/src/components/index.js
  client/src/pages/App/App.jsx
Labels: bug

#122 style: Update DetailBanner min-width 1100px
  client/src/layouts/DetailBanner/DetailBanner.jsx
  client/src/layouts/DetailBanner/DetailBanner.styled.jsx
Labels: fix

#126 Create PageNotFound page #125
  client/src/index.js
  client/src/pages/PageNotFound/PageNotFound.jsx
  client/src/pages/PageNotFound/PageNotFound.styled.jsx
  client/src/pages/index.js
  client/src/services/businesses.js
Labels: enhancement, components

#128 Set DetailPage Loading Spinner
  client/package-lock.json
  client/package.json
  client/src/components/BusinessHours/BusinessHours.jsx
  client/src/components/BusinessHours/BusinessHours.stories.jsx
  client/src/components/BusinessHours/BusinessHours.styled.jsx
  client/src/components/FilterSection/FilterSection.styled.jsx
  client/src/components/InitSVG/InitSVG.jsx
  client/src/components/Pagenation/Pagenation.jsx
  client/src/components/Pagenation/Pagenation.styled.jsx
  client/src/components/PriceFilterButton/PriceFilterButton.styled.jsx
  client/src/components/RestaurantCard/RestaurantCard.jsx
  client/src/components/Review/Reviews.jsx
  client/src/components/SearchForm/SearchForm.jsx
  client/src/index.js
  client/src/layouts/BusinessesList/BusinessesList.jsx
  client/src/layouts/DetailBanner/DetailBanner.jsx
  client/src/layouts/Footer/Footer.jsx
  client/src/layouts/Footer/Footer.styled.jsx
  client/src/layouts/GEO/GEO.jsx
  client/src/layouts/Location/Location.jsx
  client/src/layouts/Location/Location.styled.jsx
  client/src/layouts/index.js
  client/src/pages/App/App.jsx
  client/src/pages/DetailPage/DetailPage.jsx
  client/src/pages/DetailPage/DetailPage.styled.jsx
  client/src/pages/SearchPage/SearchPage.jsx
  client/src/pages/SearchPage/SearchPage.styled.jsx
  client/src/services/businesses.js
Labels: bug, enhancement

#130 Edit Detail Page layout & Add favicon
  client/public/favicon.ico
  client/src/components/BusinessHours/BusinessHours.jsx
  client/src/components/BusinessHours/BusinessHours.styled.jsx
  client/src/components/Review/Reviews.jsx
  client/src/components/Review/Reviews.styled.jsx
  client/src/components/ReviewCard/ReviewCard.jsx
  client/src/components/ReviewCard/ReviewCard.styled.jsx
  client/src/components/SortButton/SortButton.styled.jsx
  client/src/layouts/Footer/Footer.styled.jsx
  client/src/layouts/GEO/GEO.jsx
  client/src/layouts/Location/Location.jsx
  client/src/layouts/Location/Location.styled.jsx
  client/src/pages/DetailPage/DetailPage.jsx
  client/src/pages/DetailPage/DetailPage.styled.jsx
  client/src/utils/time/makeTime.js
Labels: enhancement

#134 Fix logic of fetch restaurant data
  client/src/pages/DetailPage/DetailPage.jsx
Labels: bug

#133 Refactor Code & Add React.memo #124
  client/src/api/autocomplete.js
  client/src/components/Button/Button.jsx
  client/src/components/Comment/Comment.jsx
  client/src/components/Comment/Comment.stories.jsx
  client/src/components/Comment/Comment.styled.jsx
  client/src/components/CommentList/CommentList.jsx
  client/src/components/CommentList/CommentList.styled.jsx
  client/src/components/FilterList/FilterList.jsx
  client/src/components/Icon/Icon.jsx
  client/src/components/Pagenation/Pagenation.jsx
  client/src/components/Rating/Rating.jsx
  client/src/components/RestaurantCard/RestaurantCard.jsx
  client/src/components/SearchForm/SearchForm.jsx
  client/src/components/Star/Star.jsx
  client/src/components/TitleWrapper/TitleWrapper.jsx
  client/src/components/TitleWrapper/TitleWrapper.styled.jsx
  client/src/components/index.js
  client/src/layouts/BusinessesList/BusinessesList.jsx
  client/src/layouts/DetailBanner/Carousel.jsx
  client/src/layouts/DetailBanner/DetailBanner.jsx
  client/src/layouts/DetailBanner/DetailBanner.styled.jsx
  client/src/layouts/GEO/GEO.jsx
  client/src/pages/App/App.jsx
  client/src/pages/DetailPage/DetailPage.jsx
  client/src/store/businesses.js
  client/src/store/exam.js
  client/src/store/index.js
  client/src/store/middleware.js
  client/src/utils/helper/createPageList.js
  client/src/utils/helper/createStarsArray.js
  client/src/utils/helper/index.js
  client/src/utils/helper/range0to5.js
  client/src/utils/time/makeTime.js
  server/controllers/autocomplete/index.js
  server/controllers/businesses/index.js
Labels: fix

#136 Modify README.md
  README.md
  client/README.md
  client/README.old.md
  client/src/components/FilterButton/FilterButton.jsx
  client/src/components/FilterList/FilterList.jsx
  client/src/components/FilterModal/FilterModal.jsx
  client/src/components/Review/Reviews.jsx
Labels: documentation
